/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/untitled.gltf')
  //eslint-disable-next-line
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-38, 0, -36.5]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI, 0, 0]} scale={[-1, -1, -1]} />
          <group position={[0, 0.5, 0]}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.arm2_bot_0.geometry}
              material={nodes.arm2_bot_0.material}
              skeleton={nodes.arm2_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.body_bot_0.geometry}
              material={nodes.body_bot_0.material}
              skeleton={nodes.body_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.close_bot_0.geometry}
              material={nodes.close_bot_0.material}
              skeleton={nodes.close_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.ear_bot_0.geometry}
              material={nodes.ear_bot_0.material}
              skeleton={nodes.ear_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.earBall_bot_0.geometry}
              material={nodes.earBall_bot_0.material}
              skeleton={nodes.earBall_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.earTube_bot_0.geometry}
              material={nodes.earTube_bot_0.material}
              skeleton={nodes.earTube_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eye1_bot_0.geometry}
              material={nodes.eye1_bot_0.material}
              skeleton={nodes.eye1_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eye_bot_0.geometry}
              material={nodes.eye_bot_0.material}
              skeleton={nodes.eye_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeClose1_bot_0.geometry}
              material={nodes.eyeClose1_bot_0.material}
              skeleton={nodes.eyeClose1_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeClose_bot_0.geometry}
              material={nodes.eyeClose_bot_0.material}
              skeleton={nodes.eyeClose_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeCloseKawaii1_bot_0.geometry}
              material={nodes.eyeCloseKawaii1_bot_0.material}
              skeleton={nodes.eyeCloseKawaii1_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeCloseKawaii_bot_0.geometry}
              material={nodes.eyeCloseKawaii_bot_0.material}
              skeleton={nodes.eyeCloseKawaii_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeSmile1_bot_0.geometry}
              material={nodes.eyeSmile1_bot_0.material}
              skeleton={nodes.eyeSmile1_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.eyeSmile_bot_0.geometry}
              material={nodes.eyeSmile_bot_0.material}
              skeleton={nodes.eyeSmile_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.foot_bot_0.geometry}
              material={nodes.foot_bot_0.material}
              skeleton={nodes.foot_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hand_bot_0.geometry}
              material={nodes.hand_bot_0.material}
              skeleton={nodes.hand_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.happy_bot_0.geometry}
              material={nodes.happy_bot_0.material}
              skeleton={nodes.happy_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.head_bot_0.geometry}
              material={nodes.head_bot_0.material}
              skeleton={nodes.head_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.hip_bot_0.geometry}
              material={nodes.hip_bot_0.material}
              skeleton={nodes.hip_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.index_bot_0.geometry}
              material={nodes.index_bot_0.material}
              skeleton={nodes.index_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.knee_bot_0.geometry}
              material={nodes.knee_bot_0.material}
              skeleton={nodes.knee_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.midfinger_bot_0.geometry}
              material={nodes.midfinger_bot_0.material}
              skeleton={nodes.midfinger_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.neck_bot_0.geometry}
              material={nodes.neck_bot_0.material}
              skeleton={nodes.neck_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.neckBase_bot_0.geometry}
              material={nodes.neckBase_bot_0.material}
              skeleton={nodes.neckBase_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.neckTop_bot_0.geometry}
              material={nodes.neckTop_bot_0.material}
              skeleton={nodes.neckTop_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.o_bot_0.geometry}
              material={nodes.o_bot_0.material}
              skeleton={nodes.o_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.pinky_bot_0.geometry}
              material={nodes.pinky_bot_0.material}
              skeleton={nodes.pinky_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.shoulder_bot_0.geometry}
              material={nodes.shoulder_bot_0.material}
              skeleton={nodes.shoulder_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.smile_bot_0.geometry}
              material={nodes.smile_bot_0.material}
              skeleton={nodes.smile_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.thumb_bot_0.geometry}
              material={nodes.thumb_bot_0.material}
              skeleton={nodes.thumb_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.topHead_bot_0.geometry}
              material={nodes.topHead_bot_0.material}
              skeleton={nodes.topHead_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.topHeadBall_bot_0.geometry}
              material={nodes.topHeadBall_bot_0.material}
              skeleton={nodes.topHeadBall_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.topHeadTube_bot_0.geometry}
              material={nodes.topHeadTube_bot_0.material}
              skeleton={nodes.topHeadTube_bot_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.upperLeg_bot_0.geometry}
              material={nodes.upperLeg_bot_0.material}
              skeleton={nodes.upperLeg_bot_0.skeleton}
            />
          </group>
          <group scale={[1.9, 1.9, 1.9]}>
            <group rotation={[-Math.PI, 1.5, -Math.PI]} scale={[1, 1, 1]}>
              <group rotation={[Math.PI, -1.1, Math.PI]}>
                <group position={[-1.8, 3.6, 1.3]} rotation={[-1, 1, -2.2]}>
                  <group position={[0, -0.7, 0]} scale={[0, 0, 0]}>
                    <group position={[-0.3, -0.1, -0.3]} scale={[5, 5, 5]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.pPlatonic3_holo1_0.geometry}
                        material={nodes.pPlatonic3_holo1_0.material}
                      />
                    </group>
                    <group position={[0.2, 0.1, 0]} rotation={[Math.PI, -1.5, Math.PI]}>
                      <group position={[0, 0.8, 0.2]}>
                        <group position={[0, -10.2, 0]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group rotation={[-0.5, 0, 0]} scale={[1.2, 1, 1.2]}>
                              <group scale={[3.6, 3.6, 3.6]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pCylinder2_holo1_0.geometry}
                                  material={nodes.pCylinder2_holo1_0.material}
                                />
                              </group>
                              <group scale={[3.7, 3.7, 3.7]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pCylinder3_holo1_0.geometry}
                                  material={nodes.pCylinder3_holo1_0.material}
                                />
                              </group>
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh13_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh13_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, -10.2, 0]} rotation={[0, -Math.PI / 4, 0]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group scale={[1.3, 1.3, 1.3]}>
                              <group rotation={[-0.6, -0.6, 0.1]}>
                                <group scale={[4.8, 4.8, 4.8]}>
                                  <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.pCube1_holo1_0.geometry}
                                    material={nodes.pCube1_holo1_0.material}
                                  />
                                </group>
                                <group scale={[4.9, 4.9, 4.9]}>
                                  <mesh
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.pCube2_holo1_0.geometry}
                                    material={nodes.pCube2_holo1_0.material}
                                  />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh14_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh14_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, -10.2, 0]} rotation={[Math.PI, -Math.PI / 4, Math.PI]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group rotation={[0.2, 0.2, 0.9]} scale={[1.9, 1.9, 1.9]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pTorus1_holo1_0.geometry}
                                material={nodes.pTorus1_holo1_0.material}
                              />
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pTorus2_holo1_0.geometry}
                                material={nodes.pTorus2_holo1_0.material}
                              />
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh16_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh16_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, -10.2, 0]} rotation={[Math.PI, 0, Math.PI]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group
                              position={[-0.3, 1.1, -0.4]}
                              rotation={[-0.2, -0.7, 0.3]}
                              scale={[1.6, 1.6, 1.6]}>
                              <group scale={[5.3, 7.6, 5.3]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pPyramid1_holo1_0.geometry}
                                  material={nodes.pPyramid1_holo1_0.material}
                                />
                              </group>
                              <group scale={[5.6, 8.1, 5.6]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pPyramid2_holo1_0.geometry}
                                  material={nodes.pPyramid2_holo1_0.material}
                                />
                              </group>
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh17_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh17_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group
                          position={[0, -10.2, 0]}
                          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group
                              position={[0, 0, 0]}
                              rotation={[0.5, 0.1, 0]}
                              scale={[2.4, 2.4, 2.4]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pHelix1_holo1_0.geometry}
                                material={nodes.pHelix1_holo1_0.material}
                              />
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pHelix2_holo1_0.geometry}
                                material={nodes.pHelix2_holo1_0.material}
                              />
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh18_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh18_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, -10.2, 0]} rotation={[0, 1.6, 0]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group rotation={[0.3, -0.7, 1.5]} scale={[2, 2, 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pGear1_holo1_0.geometry}
                                material={nodes.pGear1_holo1_0.material}
                              />
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pGear2_holo1_0.geometry}
                                material={nodes.pGear2_holo1_0.material}
                              />
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh19_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh19_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, -10.2, 0]} rotation={[0, Math.PI / 4, 0]}>
                          <group position={[-11.2, 10.7, 0]} scale={[0.1, 0.1, 0.1]}>
                            <group rotation={[0.5, 0, 0]} scale={[3.2, 3.2, 3.2]}>
                              <group scale={[2.1, 2.1, 2.1]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pSuperShape2_holo1_0.geometry}
                                  material={nodes.pSuperShape2_holo1_0.material}
                                />
                              </group>
                              <group scale={[2.1, 2.1, 2.1]}>
                                <mesh
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.pSuperShape3_holo1_0.geometry}
                                  material={nodes.pSuperShape3_holo1_0.material}
                                />
                              </group>
                            </group>
                            <group position={[0, 0.2, 0]} rotation={[0, 0, Math.PI / 2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.MASH1_ReproMesh12_holo1_0.geometry}
                                material={nodes.MASH1_ReproMesh12_holo1_0.material}
                              />
                            </group>
                          </group>
                        </group>
                        <group position={[0, 0.5, 0]} scale={[0.1, 0, 0.1]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.pCylinder4_holo1_0.geometry}
                            material={nodes.pCylinder4_holo1_0.material}
                          />
                        </group>
                      </group>
                      <group position={[0, -10.7, 0.2]} rotation={[0, -Math.PI / 2, 0]}>
                        <group position={[-12.4, 11.8, 0.2]} scale={[0.1, 0.1, 0.1]}>
                          <group scale={[1.4, 1.4, 1.4]}>
                            <group scale={[3.2, 3.2, 3.2]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlatonic1_holo1_0.geometry}
                                material={nodes.pPlatonic1_holo1_0.material}
                              />
                            </group>
                            <group scale={[3.4, 3.4, 3.4]}>
                              <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.pPlatonic2_holo1_0.geometry}
                                material={nodes.pPlatonic2_holo1_0.material}
                              />
                            </group>
                          </group>
                          <group
                            position={[0.2, 0, -0.5]}
                            rotation={[0, 0, Math.PI / 2]}
                            scale={[0.8, 0.8, 0.8]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.MASH1_ReproMesh15_holo1_0.geometry}
                              material={nodes.MASH1_ReproMesh15_holo1_0.material}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group position={[0, 0.4, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.MASH1_ReproMesh1_holo1_0.geometry}
                material={nodes.MASH1_ReproMesh1_holo1_0.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pPipe1_holo1_0.geometry}
                material={nodes.pPipe1_holo1_0.material}
              />
              <group position={[0, -0.6, 0]}>
                <group position={[0, 0.6, 0]} scale={[0.8, 0.8, 0.8]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MASH1_ReproMesh3_holo1_0.geometry}
                    material={nodes.MASH1_ReproMesh3_holo1_0.material}
                  />
                </group>
                <group rotation={[0, 0.7, 0]} scale={[0.9, 0.9, 0.9]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.pPipe3_holo1_0.geometry}
                    material={nodes.pPipe3_holo1_0.material}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pPipe2_holo1_0.geometry}
                  material={nodes.pPipe2_holo1_0.material}
                />
              </group>
              <group position={[0, -0.4, 0]}>
                <group position={[0, 0.4, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.MASH1_ReproMesh2_holo1_0.geometry}
                    material={nodes.MASH1_ReproMesh2_holo1_0.material}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pPipe4_holo1_0.geometry}
                  material={nodes.pPipe4_holo1_0.material}
                />
              </group>
              <group position={[0, -0.4, 0]} scale={[11.1, 11.1, 11.1]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pDisc1_holo1_0.geometry}
                  material={nodes.pDisc1_holo1_0.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group
        position={[62, 16.7, -2]}
        rotation={[-Math.PI / 2, 0, -1.6]}
        scale={[-1.1, -1.1, -1.1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.5, 11.6, 2]} rotation={[0, -1.5, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.book2_18_Books_1_4_0.geometry}
              material={nodes.book2_18_Books_1_4_0.material}
              position={[-7.7, -8.1, -22.7]}
              rotation={[0, -0.3, -0.5]}
            />
          </group>
          <group position={[-19.5, 7.4, -4.9]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.book2_x3_Books_1_4_0.geometry}
              material={nodes.book2_x3_Books_1_4_0.material}
              position={[-28, 0.2, -34.5]}
            />
          </group>
          <group position={[20.6, 9.9, 0.1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.book2_x4_Books_1_4_0.geometry}
              material={nodes.book2_x4_Books_1_4_0.material}
              position={[15.4, -4.9, -17.5]}
            />
          </group>
        </group>
      </group>
      <group position={[-63.9, 8.9, 24.8]} rotation={[-Math.PI / 2, 0, 3]} scale={[2.7, 2.7, 2.7]}>
        <group position={[-4.2, -5, -2.5]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-7.8, -8.7, -7.7]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh_0.geometry}
              material={materials.Material__64}
              position={[13.2, 0.7, 14.2]}
              rotation={[Math.PI, -0.9, Math.PI]}
            />
          </group>
        </group>
      </group>
      <group
        position={[21.3, 17.1, 53.5]}
        rotation={[-Math.PI / 2, 0, -1.3]}
        scale={[1.2, 1.2, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0001.geometry}
          material={materials['6666']}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials['7777']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.glass}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials.kanagu}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials.nose}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.steel01}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6.geometry}
          material={materials.steel2}
          position={[0, 0, -0.2]}
          rotation={[0, 0, 0]}
        />
      </group>
      <group position={[-3.6, 3.4, -16.6]} rotation={[Math.PI / 2, 0, 0]} scale={[0.4, 0.4, 0.4]}>
        <group position={[0, 0, -2.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.Eskitme3}
            position={[10, 0, 8.2]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials['steel01.001']}
        position={[-5.4, 28.9, -3.9]}
        rotation={[1.1, 0.2, -0.4]}
        scale={[17, 17, 17]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FlowerPot.geometry}
        material={materials.PotMaterial}
        position={[-67.3, 10.1, -0.8]}
        scale={[9, 9, 9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant001.geometry}
        material={nodes.Plant001.material}
        position={[-62.1, 20.1, 0.9]}
        rotation={[0, 0.1, 0.8]}
        scale={[3.7, 3.7, 3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant000.geometry}
        material={nodes.Plant000.material}
        position={[-67, 20.1, -2.5]}
        rotation={[-1.6, 1.5, 2.4]}
        scale={[3.7, 3.7, 3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant002.geometry}
        material={nodes.Plant002.material}
        position={[-65.9, 20.8, 4.7]}
        rotation={[-0.3, -1.4, 0.6]}
        scale={[3.7, 3.7, 3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plant003.geometry}
        material={nodes.Plant003.material}
        position={[-69.6, 19.9, 1.9]}
        rotation={[0, -0.2, 0.8]}
        scale={[3.7, 3.7, 3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['PotMaterial.001']}
        position={[-67.3, 8.7, -0.7]}
        scale={[7.9, 3.8, 7.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['5848152fcef1014c0b5e4967'].geometry}
        material={materials['5848152fcef1014c0b5e4967']}
        position={[-2, 35.9, -63.1]}
        rotation={[1.1, 0, -0.1]}
        scale={[13, 13, 13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['1611079'].geometry}
        material={materials['1611079']}
        position={[59.5, 36.5, 71.4]}
        rotation={[1.9, -0.2, 2.5]}
        scale={[15.1, 15.1, 15.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['5847f40ecef1014c0b5e488a'].geometry}
        material={materials['5847f40ecef1014c0b5e488a']}
        position={[3.8, 25.6, -30.3]}
        rotation={[1.1, 0.4, -0.7]}
        scale={[13, 13, 13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[-6.9, -0.2, 3.4]}
        scale={[77.7, 77.7, 77.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['1280px-Nodejs_logosvg'].geometry}
        material={materials['1280px-Node.js_logo.svg']}
        position={[-21.3, 41.4, -44.3]}
        rotation={[1.3, 0.2, -0.6]}
        scale={[18.2, 18.2, 18.2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['2560px-Npm-logosvg'].geometry}
        material={materials['2560px-Npm-logo.svg']}
        position={[-45.6, 49.5, -10.8]}
        rotation={[1.3, 0.2, -0.6]}
        scale={[10.8, 10.8, 10.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.html.geometry}
        material={materials.html}
        position={[65.9, 31.4, -0.1]}
        rotation={[1.8, -0.6, 2]}
        scale={[19.6, 19.6, 19.6]}
      />
    </group>
  )
}

useGLTF.preload('/untitled.gltf')